name = "JuliaWorkspaces"
uuid = "e554591c-7f10-434f-9f27-2097f62a04fd"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "7.0.1-DEV"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
CancellationTokens = "2e8d271d-f2e2-407b-a864-17eb2156783e"
Salsa = "1fbf2c77-44e2-4d5d-8131-0fa618a5c278"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
TestItemDetection = "76b0de8b-5c4b-48ef-a724-914b33ca988d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSONRPC = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"

[extras]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSTParser = "3.3"
JuliaSyntax = "0.4, 1"
julia = "1.10"
AutoHashEquals = "2"
CancellationTokens = "1"
Salsa = "2.2.0"
TestItemDetection = "1.1"
SHA = "<0.0.1, 0.7, 1"
Sockets = "<0.0.1, 1"
REPL = "<0.0.1, 1"
LibGit2 = "<0.0.1, 1"
InteractiveUtils = "<0.0.1, 1"
JSONRPC = "2"

[targets]
test = ["Test", "TestItemRunner"]
